### ISSUE TITLE
`checked` property not forcefully re-applied when it didn't change

### ISSUE THREAD

**Issue by zwilias** [elm/virtual-dom#117]
SSCCE: https://ellie-app.com/fkx4NH5Z3a1/0

When a view is re-rendered after an event, and a checkbox's `checked` property does not change, it will not be re-applied. We currently _do_ forcefully reapply the `value` property, presumably for the same reason.

It is surprising that this is special-cased for `value`, but not `checked`.

For reference, this is worked around for `value` in 2 places:
- include it in the `patches` here: https://github.com/elm-lang/virtual-dom/blob/master/src/Native/VirtualDom.js#L774
- forcefully `apply` it here: https://github.com/elm-lang/virtual-dom/blob/master/src/Native/VirtualDom.js#L391

Note: this can be worked around with `Keyed` by [bumping a counter](https://ellie-app.com/fkx4NH5Z3a1/1) so Elm doesn't reuse the DOM-node. It's a weird workaround, given that it works intuitively for `input [ value ... ]`.

**Comment by gyzerok** [comment]
Here is a bit bigger example: https://ellie-app.com/gmpVHd97pa1/0

Reproduce:
1. Check 2
2. Click button

**Comment by aforemny** [comment]
I have hit the same problem with a `<select>` `selectedIndex` property.

**Comment by kjarnet** [comment]
Thanks for the `Keyed` workaround, and to @aforemny for describing the problem with `<select>`s, which let me find this issue!

Recently coming to Elm from React, I expected `Html.select` to work like a React "controlled component", as `Html.input` does, and, when it didn't, struggled a lot (including trying `preventDefault`, as @aforemny also mentions) before finding this issue and workaround. So +1 from me for fixing this in virtual-dom!

**Comment by evancz** [comment]
Thank you for the report @zwilias! LMK if the fix looks correct to you.
