### ISSUE TITLE
Blur event handler causes the virtual dom to lose track of nodes

### ISSUE THREAD

**Issue by larribas** [elm/virtual-dom#126]
Here is a somewhat minimal example:

https://gist.github.com/larribas/b47e3f63e8134aa855595f11f429ef56

This is the initial state

![screenshot_20180515_130214](https://user-images.githubusercontent.com/3601671/40053124-6a01eedc-5840-11e8-86f3-0ce5e4b53a49.png)

This is the state after writing a new item

![screenshot_20180515_130245](https://user-images.githubusercontent.com/3601671/40053141-7702b436-5840-11e8-9b32-e3843c01246a.png)

And then if we repeat that action many times goes on

![screenshot_20180515_130315](https://user-images.githubusercontent.com/3601671/40053157-8526d6aa-5840-11e8-9b4d-e44627a6107d.png)

This is what Chrome's console says each time it happens:

```
Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at _VirtualDom_applyPatchRedraw (demo.js:3355:14)
    at _VirtualDom_applyPatch (demo.js:3276:11)
    at _VirtualDom_applyPatchesHelp (demo.js:3262:17)
    at _VirtualDom_applyPatches (demo.js:3253:9)
    at demo.js:3651:14
    at demo.js:3686:8
    at sendToApp (demo.js:1494:3)
    at HTMLTextAreaElement.callback (demo.js:2552:3)
```

**Comment by larribas** [comment]
I discovered the issue while upgrading this library: https://github.com/larribas/elm-multi-input
Which worked fine for elm 0.18

**Comment by hecrj** [comment]
Here is a shorter SSCCE:

https://gist.github.com/hecrj/ce06033689dca3eb603acdbbdaf2eb51

**Comment by evancz** [comment]
Switching `onBlur` to be on `requestAnimationFrame` fixes this. It seems that `onblur` does some [strange things](https://stackoverflow.com/questions/21926083/failed-to-execute-removechild-on-node) such that asynchronous seems to be a safer default.
