### ISSUE TITLE
XSS filter can be bypassed

### ISSUE THREAD

**Issue by antew** [elm/virtual-dom#129]
Affects version: 0.19

A tab character embedded in an `href` will get around the filter, clicking the link in this example will show an alert.
```
a [ href "java	script: alert('hello')" ] [ text "click me" ]
```

SSCE
https://ellie-test-19-cutover.now.sh/PhT7CbsG3Pa1

**Comment by evancz** [comment]
Thanks for the report. The new test should be stronger, but please let me know if you find any others. Now is a great time to fix them!
