### ISSUE TITLE
Assigning an empty string value to an attribute is not possible

### ISSUE THREAD

**Issue by tbash** [elm/virtual-dom#132]
This highlights a behavior change in 0.19 from 0.18.

Given the following SSCCE:
```elm
module Main exposing (main)

import Html exposing (Html)
import Html.Attributes as Attributes


main : Html msg
main =
    Html.button
        [ Attributes.attribute "visible-on-document" ""
        ]
        [ Html.text "Hello, World!"
        ]
```
The HTML generated using 0.18 would be:
```html
<button visible-on-document>Hello, World!</button>
```
The HTML generated using 0.19 is:
```html
<button>Hello, World!</button>
```
Perhaps this change is for the best, the intention behind this kind of attribute is for flagging the attribute as true, implicitly. This specific use case is to make the button above selectable by some parent element using `parent.querySelector("[visible-on-document]")`, maybe using `Attributes.attribute "visible-on-document" "any-value"` is better? Any primitive elements I can think of that correctly make use of boolean attributes have property setters that can be used in place of attribute assignment (e.g. input nodes have `input.disabled = true` that modifies the element to appear as `<input disabled></input>`, doing `input.setAttribute("disabled", "")` can achieve the same thing).

**Comment by Pilatch** [comment]
I argue that this behavior is not for the best, as it's confusing. Furthermore HTML has valid attributes that do not take values, such as defer/async in script tags. Granted, you're probably making script tags with Elm, but for users of custom elements, it makes a lot of sense to have boolean attributes that are targeted by CSS. Here's an example of my own - https://www.npmjs.com/package/pilatch-card#usage

The alternative is for me to give these attributes a single-space blank string, which introduces noise in the markup that I don't need to see when debugging.
