### ISSUE TITLE
input bound value leads to cursor jumping on every keystroke

### ISSUE THREAD

**Issue by littleStudent** [elm/virtual-dom#138]
I have a bound input element. So the state property storing the value is bound back to the dom element. On every keystroke this leads to the cursor jumping to the end of the input.

SSCCCE: https://ellie-app.com/3dWX47DKWwPa1
Browser: Safari (macOS & iOS confirmed)

![input-cursor-jumping](https://user-images.githubusercontent.com/815520/44990633-ec0a0b00-af91-11e8-8923-d3a8256b0824.gif)

```Elm
module Main exposing (main)

import Browser
import Html exposing (Html, input)
import Html.Attributes exposing (value)
import Html.Events exposing (onInput)

type Msg
    = OnInput String

main : Program () String Msg
main =
    Browser.sandbox
        { init = ""
        , view = \str -> input [ onInput OnInput, value str ] []
        , update = \(OnInput str) _ -> str
        }


```

**Comment by harrysarson** [comment]
Note this *only* happens on Safari.

**Comment by norpan** [comment]
If nodes are updated by setting `value`, this is the specified behavior:
https://html.spec.whatwg.org/multipage/input.html#dom-input-value-value

I'm not sure why it works in other browsers though.

So you'd have to do something like:
```
var start = element.selectionStart;
var end = element.selectionEnd;

element.value = newValue;

element.setSelectionRange(start, end);
```

**Comment by norpan** [comment]
Also see https://github.com/whatwg/html/issues/2412

**Comment by jinjor** [comment]
See also https://github.com/elm/html/issues/174

**Comment by decioferreira** [comment]
this relates to elm/virtual-dom/issues/134 and elm/virtual-dom/pull/135

**Comment by digitalsatori** [comment]
same problem here, the problem found only on input element, textarea is OK.  Safari only.

![elm_input_problem](https://user-images.githubusercontent.com/140909/45430783-baebb200-b6d8-11e8-850a-00c2761600f4.gif)

**Comment by evancz** [comment]
Some core team folks reviewed https://github.com/elm/virtual-dom/pull/135, and they tell me it should fix this. Can do a patch soon.

**Comment by lucamug** [comment]
To avoid confusion in case people hit this old issue:

It has been fixed in virtual-dom v.1.0.1 (https://github.com/elm/virtual-dom/releases/tag/1.0.1) released on Sep 13, 2018.

This is an Ellie for it: https://ellie-app.com/9d3gvnKDT2ra1

This issue is also mentioned in

https://github.com/elm/virtual-dom/issues/107
https://github.com/elm/html/issues/105
https://github.com/elm/html/issues/42
https://github.com/elm/html/issues/62
