### ISSUE TITLE
Logic bug in `_VirtualDom_applyFacts`

### ISSUE THREAD

**Issue by hpate-omicron** [elm/virtual-dom#139]
I noticed this while reading through the code, the conditional checks on https://github.com/elm/virtual-dom/blob/master/src/Elm/Kernel/VirtualDom.js#L496 will always return `true`

```
(key !== 'value' || key !== 'checked' || domNode[key] !== value) && (domNode[key] = value);
```

Any string will pass `key !== 'value' || key !== 'checked'`

**Comment by evancz** [comment]
Some core team folks reviewed https://github.com/elm/virtual-dom/pull/135, and they tell me it should fix this. Can do a patch soon.
